M48
; DRILL file {KiCad 7.0.8} date Sat Dec 16 16:38:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-16T16:38:24-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X6.8256Y-3.1045
X6.8256Y-3.2955
T2
X6.9449Y-3.0927
X6.9449Y-3.3073
T0
M30
